// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateWalletPayload struct {
	OwnerAddress string `json:"owner_address"`
	Salt         int    `json:"salt"`
	NetworkID    string `json:"network_id"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUp struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type Wallet struct {
	Address      string `json:"address"`
	OwnerAddress string `json:"owner_address"`
	Salt         int    `json:"salt"`
	NetworkID    string `json:"network_id"`
}
